local M = {
  NO_RECIPE_OR_STOCK = "NO_RECIPE_OR_STOCK",
  ITEM_NOT_REACHABLE = "ITEM_NOT_REACHABLE",
  INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",
  DEADLOCK = "DEADLOCK",
  NO_COMPATIBLE_MACHINE = "NO_COMPATIBLE_MACHINE",
  CRAFT_FAILED = "CRAFT_FAILED",
  MUTATE_AFTER_SNAPSHOT = "MUTATE_AFTER_SNAPSHOT",
  BUFFER_NEGATIVE = "BUFFER_NEGATIVE",
  CYCLE_DETECTED = "CYCLE_DETECTED",
  SNAPSHOT_TAKEN = "SNAPSHOT_TAKEN",
  GET_AFTER_SNAPSHOT = "GET_AFTER_SNAPSHOT",
  OUTPUTS_COLLECTED = "OUTPUTS_COLLECTED",
  OUTPUTS_NOT_READY = "OUTPUTS_NOT_READY",
  NEGATIVE_COUNT = "NEGATIVE_COUNT",
  UNLOCK_NON_BUSY = "UNLOCK_NON_BUSY",
  UNKNOWN_STEP = "UNKNOWN_STEP",
  TASK_TIMEOUT = "TASK_TIMEOUT",
}

return M
